name: learning_flutter
description: Generatore Password

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  serial_number: ^0.1.0
  crypto: ^2.1.4
  intl: ^0.16.0
  path_provider: "^0.4.1"
  percent_indicator: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - images/chiave.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
